In [1]:
import tensorflow as tf
import numpy as np # dependency library

C:\Users\srikanth\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
tf.__version__

'1.10.0'

In [ ]:
a = 2
b=  3
c = a+b

In [ ]:
c

# Tensorflow 

- constant
- variable
- placholders

In [3]:
# addtion in tensorflow
a = tf.constant(2,name='x1')# name = anything without space
b = tf.constant(3,name='x2')

In [4]:
c = tf.add(a,b,name='addition')

In [5]:
c

<tf.Tensor 'addition:0' shape=() dtype=int32>

In [6]:
# Running graph
with tf.Session() as sess:
    result = sess.run(c)
    print(result)

5


In [7]:
# writing graph
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./firstgraph',graph=sess.graph)
    res_a = sess.run(a)
    res_b = sess.run(b)
    res = sess.run(c)
    print(res_a,res_b,res)
    writer.close()

2 3 5


# Graph 2

In [9]:
# input layer
x1 = tf.constant(1,dtype=tf.float32,name='a')
x2 = tf.constant(2,dtype=tf.float32,name='b')
x3 = tf.constant(3,dtype=tf.float32,name='c')

# Layer - 1

L1 = tf.add(x1,x2,name='layer_1')

# Layer- 2
L21 = tf.multiply(L1,x3,name='Layer_21')
L22 = tf.add(x1,tf.add(x2,x3),name='layer_22')

# Layer-3
L3 = L21 + L22

# output 
output = tf.sin(L3,name='ouput')

In [10]:
# writing grph
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./secondgraph',graph=sess.graph)
    result = sess.run(output)
    print(result)
    writer.close()

0.65028787


# Graph 3

In [11]:
# step -1 : creating a placeholder
x = tf.placeholder(dtype=tf.float32,shape=(3,1),
                  name='input')

# step-2 : weight
w_rand = tf.random_normal(shape=(3,3))
W = tf.Variable(initial_value=w_rand)

# Step-3: Layer-1

L1 = tf.matmul(W,x,name='Layer1') # shape = 3x1

# step-4: weight
w1_rand = tf.random_normal(shape=(3,1))
W1 = tf.Variable(initial_value=(w1_rand))# 3x1

# step-5: output
output = tf.matmul(W1,L1,transpose_a=True) # (1x1)


In [12]:
a = np.ones(shape=(3,1))
a.shape

(3, 1)

In [13]:
a

array([[1.],
       [1.],
       [1.]])

In [14]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    writer = tf.summary.FileWriter(logdir="./srikanth",
                              graph=sess.graph)
    result = sess.run(output,feed_dict={x:a})
    print(result)
    writer.close()

[[4.872452]]


In [4]:
x = tf.placeholder(dtype=tf.float32,shape=3,name='inputs')

In [5]:
# Layer - 1

L1 = tf.add(x[0],x[1],name='layer_1')

# Layer- 2
L21 = tf.multiply(L1,x[2],name='Layer_21')
L22 = tf.add(x1,tf.add(x[1],x[2]),name='layer_22')

# Layer-3
L3 = L21 + L22

# output 
output = tf.sin(L3,name='ouput')

In [6]:
# writing grph
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./thirdgraph',graph=sess.graph)
    result = sess.run(output,feed_dict={x:[6,7,8]})
    print(result)
    writer.close()

0.58061117


# Graph 4

> ### Variable

**creating 3 x 3 matrix**

In [7]:
w = tf.random_uniform(shape=(3,3))

In [9]:
v1 = tf.Variable(initial_value=w,name='varaibe')

In [11]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(v1))

[[0.7657981  0.36485493 0.11041331]
 [0.2429986  0.617679   0.08694744]
 [0.9450878  0.15198946 0.8951292 ]]
